# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\"\xa1\x01\n\x06Sensor\x12\x10\n\x08playerID\x18\x01 \x02(\x05\x12\x10\n\x08\x62\x65\x65tleID\x18\x02 \x02(\x05\x12 \n\x07payload\x18\x03 \x03(\x0b\x32\x0f.Sensor.IMUdata\x1aQ\n\x07IMUdata\x12\n\n\x02\x61\x31\x18\x01 \x02(\x02\x12\n\n\x02\x61\x32\x18\x02 \x02(\x02\x12\n\n\x02\x61\x33\x18\x03 \x02(\x02\x12\n\n\x02g1\x18\x04 \x02(\x02\x12\n\n\x02g2\x18\x05 \x02(\x02\x12\n\n\x02g3\x18\x06 \x02(\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSOR._serialized_start=17
  _SENSOR._serialized_end=178
  _SENSOR_IMUDATA._serialized_start=97
  _SENSOR_IMUDATA._serialized_end=178
# @@protoc_insertion_point(module_scope)
