# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tengk/mlp_HLS/mlp_HLS.srcs/sources_1/bd/design_3/ip/design_3_axi_dma_0_0/design_3_axi_dma_0_0.xci
# IP: The module: 'design_3_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tengk/mlp_HLS/mlp_HLS.srcs/sources_1/bd/design_3/ip/design_3_axi_dma_0_0/design_3_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tengk/mlp_HLS/mlp_HLS.srcs/sources_1/bd/design_3/ip/design_3_axi_dma_0_0/design_3_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tengk/mlp_HLS/mlp_HLS.srcs/sources_1/bd/design_3/ip/design_3_axi_dma_0_0/design_3_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/tengk/mlp_HLS/mlp_HLS.srcs/sources_1/bd/design_3/ip/design_3_axi_dma_0_0/design_3_axi_dma_0_0.xci
# IP: The module: 'design_3_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tengk/mlp_HLS/mlp_HLS.srcs/sources_1/bd/design_3/ip/design_3_axi_dma_0_0/design_3_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tengk/mlp_HLS/mlp_HLS.srcs/sources_1/bd/design_3/ip/design_3_axi_dma_0_0/design_3_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tengk/mlp_HLS/mlp_HLS.srcs/sources_1/bd/design_3/ip/design_3_axi_dma_0_0/design_3_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
