# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_3/design_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_dma_0_0/design_3_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_axi_dma_0_0 || ORIG_REF_NAME==design_3_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_mlp_HLS_0_0/design_3_mlp_HLS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_mlp_HLS_0_0 || ORIG_REF_NAME==design_3_mlp_HLS_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_zynq_ultra_ps_e_0_0/design_3_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_3_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xbar_0/design_3_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_xbar_0 || ORIG_REF_NAME==design_3_xbar_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_ps8_0_axi_periph_0/design_3_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_3_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_rst_ps8_0_99M_0/design_3_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_3_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_smc_0/design_3_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_axi_smc_0 || ORIG_REF_NAME==design_3_axi_smc_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_bram_ctrl_0_0/design_3_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_3_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_bram_ctrl_0_bram_0/design_3_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_3_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_auto_ds_0/design_3_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_auto_ds_0 || ORIG_REF_NAME==design_3_auto_ds_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_auto_pc_0 || ORIG_REF_NAME==design_3_auto_pc_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_auto_ds_1/design_3_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_auto_ds_1 || ORIG_REF_NAME==design_3_auto_ds_1} -quiet] -quiet

# XDC: bd/design_3/design_3_ooc.xdc
